/*
 * File: app/view/customerViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.customerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmcustomer',
    requries:[        
        'Vidly.store.membershipType',
        'Vidly.store.customers',
    ],
    
    show:function(){
        "use strict";
        var me = this;

        me.getView().show();
        var context = me.setupContext();
        context.data.load();
    },
    setupContext:function(){
        var me =this,
            win= me.getView();
        
        win.context = Ext.create('iRely.Engine',{
            window:win,
            store:Ext.create('Vidly.store.customers'),
            singleGridMgr:Ext.create('iRely.grid.Manager',{
                grid:win.down('grid'),
                title:'Customers Window',
                columns:[
                    {
                        xtype:'gridcolumn',
                        text:'Customer Name',
                        itemId:'fldcolFullName',
                        dataType:'string',
                        dataIndex:'strFullName',
                        flex:1,
                        editor:{
                            xtype:'textfield',
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Birth Date',
                        itemId:'colBirthDate',
                        dataType:'date',
                        dataIndex:'dtmBirthDate',
                        flex:1,
                        editor:{
                            xtype:'datefield',
                            format: 'c',
                            dateWriteFormat: 'C'
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        dataIndex:'strMembershipName',   
                        text:'Membership Type',
                        flex:1,
                        editor:{
                            xtype:'gridcombobox',
                            columns:[
                                {
                                    dataIndex: 'intMembeshipTypeId',
                                    dataType: 'int',
                                    hidden: true
                                },
                                {
                                    dataIndex: 'strMembershipName',
                                    dataType: 'string',
                                    flex: 1
                                }
                            ],                  
                            displayField:'strMembershipName',
                            valueField:'strMembershipName',
                            origValueField:'intMembeshipTypeId',
                            store:Ext.create('Vidly.store.membershipType')
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Discount',
                        itemId:'colDiscount',
                        dataType:'string',
                        dataIndex:'dblDiscount',
                        flex:1,
                        editor:{
                            xtype:'textfield',
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Subscribed to News Letter',
                        itemId:'colIsSubscribedToNewsLetter',
                        dataType:'bool',
                        dataIndex:'ysnIsSubscribedToNewsLetter',
                        flex:1,
                        editor:{
                            xtype:'checkboxfield',
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Delingquent',
                        itemId:'colIsDelenquent',
                        dataType:'bool',
                        dataIndex:'ysnIsDelenquent',
                        flex:1,
                        editor:{
                            xtype:'checkboxfield',
                        }
                    },
                ],

            })
        });
        return win.context;
    }


});
