/*
 * File: app/view/moviesViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.moviesViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmmovies',
    requries:[        
        'Vidly.store.movies',
        'Vidly.store.genre'
    ],
    show:function(){
        "use strict";
        var me = this;

        me.getView().show();
        var context = me.setupContext();
        context.data.load();
    },
    setupContext:function(){
        var me =this,
            win= me.getView();
        win.context = Ext.create('iRely.Engine',{
            window:win,
            store:Ext.create('Vidly.store.movies'),
            singleGridMgr:Ext.create('iRely.grid.Manager',{
                grid:win.down('grid'),
                title:'Movies Window',
                columns:[
                    {
                        xtype:'gridcolumn',
                        text:'Movie Title',
                        itemId:'colTitle',
                        dataType:'string',
                        dataIndex:'strTitle',
                        flex:1,
                        editor:{
                            xtype:'textfield'
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Genre',
                        itemId:'colGenre',
                        dataType:'string',
                        dataIndex:'strGenreName',
                        flex:1,
                        editor:{
                            xtype:'gridcombobox',
                            columns:[
                                {
                                    dataIndex: 'intGenreId',
                                    dataType: 'int',
                                    hidden: true
                                },
                                {
                                    dataIndex: 'strGenreName',
                                    dataType: 'string',
                                    flex: 1
                                }
                            ],
                            displayField:'strGenreName',
                            valueField:'strGenreName',
                            origValueField:'intGenreId',
                            store:Ext.create('Vidly.store.genre')
                        }
                    },
                    
                    {
                        xtype:'gridcolumn',
                        text:'Movie Price',
                        itemId:'colMoviePrice',
                        dataType:'number',
                        dataIndex:'dblMoviePrice',
                        flex:1,
                        editor:{
                            xtype:'textfield',
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Release Date',
                        itemId:'colReleaseDate',
                        dataType:'date',
                        dataIndex:'dtmReleaseDate',
                        flex:1,
                        editor:{
                            xtype:'datefield',
                            format: 'c',
                            dateWriteFormat: 'c'
                        }
                    },
                    {
                        xtype:'gridcolumn',
                        text:'Total Stocks',
                        itemId:'colTotalStocks',
                        dataType:'number',
                        dataIndex:'intTotalStocks',
                        flex:1,
                        editor:{
                            xtype:'textfield',
                        }
                    },
                    
                ]
            })
        });
        return win.context;
    }

});
