/*
 * File: app/view/newTransactionViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.newtransactionViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmnewtransaction',
    config:{
        bindings:{
            grdSelectMovies:{
                 store:'{movieList}',
                 colMovieTitle:
                 {
                     dataIndex:'strTitle'
                 }
            }
        }
    },

    show: function (config) {
        "use strict";
        var me = this,
            win = me.getView(),
            action = config && config.action;

        if (action) {
            win.show();
            
        }
    },

    

   
});
