/*
 * File: app/view/newtransaction.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.newtransaction', {
    extend: 'Ext.window.Window',
    alias: 'widget.newtransaction',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number'
    ],

    controller: 'frmnewtransaction',
    viewModel: 'frmnewtransaction',
    height: 685,
    itemId: 'frmnewTransaction',
    width: 1122,
    title: 'New Transaction Window',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnSave',
                    ui: 'i21-button-toolbar-small',
                    text: 'Save'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'container',
                    padding: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txttransactionID',
                                    fieldLabel: 'Transaction Id'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtCustomerName',
                                    fieldLabel: 'Customer Name'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'grdSelectMovies',
                            title: 'Choose Movies',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    itemId: 'colMovieTitle',
                                    dataIndex: 'strTitle',
                                    text: 'Movie Title'
                                },
                                {
                                    xtype: 'datecolumn',
                                    flex: 1,
                                    itemId: 'colReleaseDate',
                                    dataIndex: 'dtmReleaseDate',
                                    text: 'Release Date'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    flex: 1,
                                    itemId: 'colAvailStocks',
                                    dataIndex: 'intTotalStocks',
                                    text: 'Avaiable Stocks'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});