/*
 * File: app/view/transactions.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.transactions', {
    extend: 'Ext.window.Window',
    alias: 'widget.frmtransactions',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.selection.RowModel',
        'Ext.form.field.Hidden',
        'Vidly.common.combobox.Customer'
    ],

    height: 685,
    width: 1122,
    layout: 'fit',
    title: 'Rental Transaction',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New',
                            listeners: {
                                click: 'onBtnNewClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save',
                            listeners: {
                                click: 'onBtnSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Find'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Detail',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'ctnHeader',
                                    padding: 10,
                                    items: [
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'txtTransactionId',
                                                    fieldLabel: 'Transaction Id',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtCustomerName',
                                                    fieldLabel: 'Customer Name',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'customercombo',
                                                    lookUpField: true,
                                                    enableDrillDown: true,
                                                    itemId: 'cboCustomerName',
                                                    fieldLabel: 'Customer Name',
                                                    displayField: 'strFullName',
                                                    forceSelection: true,
                                                    valueField: 'strFullName'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'ctnDetail',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'frmadvancesearchgrid',
                                            height: 250,
                                            itemId: 'grdRentedMovies',
                                            title: 'Rented Movies',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    componentCls: 'i21-toolbar-grid',
                                                    itemId: 'tblGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnAddMovies',
                                                            iconCls: 'small-insert',
                                                            text: 'Add'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDeleteMovies',
                                                            iconCls: 'small-remove',
                                                            text: 'Delete'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    itemId: 'colMovieName',
                                                    dataIndex: 'string',
                                                    text: 'Movie Name'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    flex: 1,
                                                    itemId: 'colMoviePrice',
                                                    dataIndex: 'number',
                                                    text: 'Movie Price'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    flex: 1,
                                                    itemId: 'colDateBorrowed',
                                                    dataIndex: 'date',
                                                    text: 'Date Borrowed'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    flex: 1,
                                                    itemId: 'colDateReturned',
                                                    dataIndex: 'date',
                                                    text: 'Date Returned'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    flex: 1,
                                                    itemId: 'colIsReturned',
                                                    text: 'Returned'
                                                }
                                            ],
                                            listeners: {
                                                select: 'onGrdRentedMoviesSelect'
                                            },
                                            selModel:Ext.create('Ext.selection.CheckboxModel', {
                                                selType: 'checkboxmodel'
                                            }),
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    itemId: 'frmMovieDetail',
                                    bodyPadding: 10,
                                    title: 'Rental Info',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtMovieName',
                                                    fieldLabel: 'Movie Name',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtReturnedDate',
                                                    fieldLabel: 'Return Date',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtPayment',
                                                    fieldLabel: 'Payment:',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnReturnMovies',
                                                    text: 'Return Movies',
                                                    listeners: {
                                                        click: 'onBtnReturnMoviesClick'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            flex: 1,
                                            itemId: 'txtRentalId',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        close: 'onWindowClose'
    },

    onWindowClose: function(panel, eOpts) {

    }

});